[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airtable-json-uploader"
version = "0.1.0"
description = "A package to process JSON files, map keys to Airtable table columns, and update Airtable records."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=1.0.0",
    "flask>=2.0.0",
    "openpyxl>=3.0.0"
]


[project.scripts]
airtable-upload = "airtable_json_uploader.cli:main"
airtable-web = "airtable_json_uploader.app:main"
airtable-extract = "airtable_json_uploader.cli:extract_cli"
azoogi-version = "airtable_json_uploader.cli:version_cli"
